apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;
        server_name 8.217.47.128;
        
        location / {
          proxy_pass http://18.163.81.11;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name hellohk.world;

        ssl_certificate /data/hellohk.world/fullchain.pem;
        ssl_certificate_key /data/hellohk.world/privkey.pem;

        location / {
          proxy_pass http://18.163.81.11;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
